// Code generated by goctl. DO NOT EDIT.
// Source: portal.proto

package portalclient

import (
	"context"

	"zerocmf/service/portal/rpc/types/portal"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SiteReply = portal.SiteReply
	SiteReq   = portal.SiteReq

	Portal interface {
		AutoMigrate(ctx context.Context, in *SiteReq, opts ...grpc.CallOption) (*SiteReply, error)
	}

	defaultPortal struct {
		cli zrpc.Client
	}
)

func NewPortal(cli zrpc.Client) Portal {
	return &defaultPortal{
		cli: cli,
	}
}

func (m *defaultPortal) AutoMigrate(ctx context.Context, in *SiteReq, opts ...grpc.CallOption) (*SiteReply, error) {
	client := portal.NewPortalClient(m.cli.Conn())
	return client.AutoMigrate(ctx, in, opts...)
}
