// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admincategory "zerocmf/service/shop/api/internal/handler/admin/category"
	adminproduct "zerocmf/service/shop/api/internal/handler/admin/product"
	appproduct "zerocmf/service/shop/api/internal/handler/app/product"
	"zerocmf/service/shop/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: admincategory.GetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/treeData",
					Handler: admincategory.GetTreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:id",
					Handler: admincategory.ShowHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: admincategory.StoreHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:id",
					Handler: admincategory.EditHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: admincategory.DelHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/",
					Handler: admincategory.BatchDelHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/shop/admin/categories"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: adminproduct.GetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:productId",
					Handler: adminproduct.ShowHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/",
					Handler: adminproduct.StoreHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/:productId",
					Handler: adminproduct.EditHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: adminproduct.DelHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/",
					Handler: adminproduct.BatchDelHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/shop/admin/products"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WxappMiddleware, serverCtx.SiteMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/tree",
					Handler: appproduct.TreeHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/",
					Handler: appproduct.GetHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:productId",
					Handler: appproduct.ShowHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/shop/app/products"),
	)
}
