// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package productservice

import (
	"context"

	"zerocmf/service/shop/rpc/pb/shop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CategoryDelReq       = shop.CategoryDelReq
	CategoryGetReq       = shop.CategoryGetReq
	CategoryListResp     = shop.CategoryListResp
	CategoryResp         = shop.CategoryResp
	CategorySaveReq      = shop.CategorySaveReq
	CategoryShowReq      = shop.CategoryShowReq
	CategoryTreeData     = shop.CategoryTreeData
	CategoryTreeListResp = shop.CategoryTreeListResp
	CategoryTreeReq      = shop.CategoryTreeReq
	ProductAttrKeyReq    = shop.ProductAttrKeyReq
	ProductAttrKeyResp   = shop.ProductAttrKeyResp
	ProductAttrValReq    = shop.ProductAttrValReq
	ProductAttrValResp   = shop.ProductAttrValResp
	ProductSaveReq       = shop.ProductSaveReq
	ProductSaveResp      = shop.ProductSaveResp
	ProductSku           = shop.ProductSku

	ProductService interface {
		ProductSave(ctx context.Context, in *ProductSaveReq, opts ...grpc.CallOption) (*ProductSaveResp, error)
	}

	defaultProductService struct {
		cli zrpc.Client
	}
)

func NewProductService(cli zrpc.Client) ProductService {
	return &defaultProductService{
		cli: cli,
	}
}

func (m *defaultProductService) ProductSave(ctx context.Context, in *ProductSaveReq, opts ...grpc.CallOption) (*ProductSaveResp, error) {
	client := shop.NewProductServiceClient(m.cli.Conn())
	return client.ProductSave(ctx, in, opts...)
}
