// Code generated by goctl. DO NOT EDIT.
// Source: portal.proto

package server

import (
	"context"

	"zerocmf/service/portal/rpc/internal/logic"
	"zerocmf/service/portal/rpc/internal/svc"
	"zerocmf/service/portal/rpc/types/portal"
)

type PortalServer struct {
	svcCtx *svc.ServiceContext
	portal.UnimplementedPortalServer
}

func NewPortalServer(svcCtx *svc.ServiceContext) *PortalServer {
	return &PortalServer{
		svcCtx: svcCtx,
	}
}

func (s *PortalServer) AutoMigrate(ctx context.Context, in *portal.SiteReq) (*portal.SiteReply, error) {
	l := logic.NewAutoMigrateLogic(ctx, s.svcCtx)
	return l.AutoMigrate(in)
}
