// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	thirdPartverify "zerocmf/service/wechat/api/internal/handler/thirdPart/verify"
	"zerocmf/service/wechat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/component_verify_ticket",
				Handler: thirdPartverify.GetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/wechat"),
	)
}
