// Code generated by goctl. DO NOT EDIT.
package types

import (
	"github.com/jinzhu/copier"
	bsData "zerocmf/common/bootstrap/data"
)

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type TokenReq struct {
	Usermame string `json:"username,optional"`
	Password string `json:"password,optional"`
}

type SiteGetReq struct {
}

type SiteShowReq struct {
	SiteId int64 `path:"siteId,optional"`
}

type SiteSaveReq struct {
	SiteId    int     `path:"siteId,optional"`
	Name      string  `json:"name"`
	Desc      string  `json:"desc,optional"`
	Domain    string  `json:"domain,optional"`
	Dsn       string  `json:"dsn,optional"`
	ListOrder float64 `json:"listOrder,optional"`
	Status    *int    `json:"status,optional"`
}

type SiteDomainReq struct {
	Domain string `path:"domain"`
}

func (r *Response) Success(msg string, data interface{}) {
	success := new(bsData.Rest).Success(msg, data)
	copier.Copy(&r, &success)
	return
}

func (r *Response) Error(msg string, data interface{}) {
	err := new(bsData.Rest).Error(msg, data)
	copier.Copy(&r, &err)
	return
}
