// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package server

import (
	"context"

	"zerocmf/service/shop/rpc/internal/logic/productattrservice"
	"zerocmf/service/shop/rpc/internal/svc"
	"zerocmf/service/shop/rpc/pb/shop"
)

type ProductAttrServiceServer struct {
	svcCtx *svc.ServiceContext
	shop.UnimplementedProductAttrServiceServer
}

func NewProductAttrServiceServer(svcCtx *svc.ServiceContext) *ProductAttrServiceServer {
	return &ProductAttrServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductAttrServiceServer) AttrKeySave(ctx context.Context, in *shop.ProductAttrKeyReq) (*shop.ProductAttrKeyResp, error) {
	l := productattrservicelogic.NewAttrKeySaveLogic(ctx, s.svcCtx)
	return l.AttrKeySave(in)
}

func (s *ProductAttrServiceServer) AttrValSave(ctx context.Context, in *shop.ProductAttrValReq) (*shop.ProductAttrValResp, error) {
	l := productattrservicelogic.NewAttrValSaveLogic(ctx, s.svcCtx)
	return l.AttrValSave(in)
}
