// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package productattrservice

import (
	"context"

	"zerocmf/service/shop/rpc/pb/shop"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CategoryDelReq       = shop.CategoryDelReq
	CategoryGetReq       = shop.CategoryGetReq
	CategoryListResp     = shop.CategoryListResp
	CategoryResp         = shop.CategoryResp
	CategorySaveReq      = shop.CategorySaveReq
	CategoryShowReq      = shop.CategoryShowReq
	CategoryTreeData     = shop.CategoryTreeData
	CategoryTreeListResp = shop.CategoryTreeListResp
	CategoryTreeReq      = shop.CategoryTreeReq
	ProductAttrKeyReq    = shop.ProductAttrKeyReq
	ProductAttrKeyResp   = shop.ProductAttrKeyResp
	ProductAttrValReq    = shop.ProductAttrValReq
	ProductAttrValResp   = shop.ProductAttrValResp
	ProductSaveReq       = shop.ProductSaveReq
	ProductSaveResp      = shop.ProductSaveResp
	ProductSku           = shop.ProductSku

	ProductAttrService interface {
		AttrKeySave(ctx context.Context, in *ProductAttrKeyReq, opts ...grpc.CallOption) (*ProductAttrKeyResp, error)
		AttrValSave(ctx context.Context, in *ProductAttrValReq, opts ...grpc.CallOption) (*ProductAttrValResp, error)
	}

	defaultProductAttrService struct {
		cli zrpc.Client
	}
)

func NewProductAttrService(cli zrpc.Client) ProductAttrService {
	return &defaultProductAttrService{
		cli: cli,
	}
}

func (m *defaultProductAttrService) AttrKeySave(ctx context.Context, in *ProductAttrKeyReq, opts ...grpc.CallOption) (*ProductAttrKeyResp, error) {
	client := shop.NewProductAttrServiceClient(m.cli.Conn())
	return client.AttrKeySave(ctx, in, opts...)
}

func (m *defaultProductAttrService) AttrValSave(ctx context.Context, in *ProductAttrValReq, opts ...grpc.CallOption) (*ProductAttrValResp, error) {
	client := shop.NewProductAttrServiceClient(m.cli.Conn())
	return client.AttrValSave(ctx, in, opts...)
}
