// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	wxopenadmin "zerocmf/service/wechat/api/internal/handler/wxopen/admin"
	wxopenappfastRegisterWeApp "zerocmf/service/wechat/api/internal/handler/wxopen/app/fastRegisterWeApp"
	wxopenapplogin "zerocmf/service/wechat/api/internal/handler/wxopen/app/login"
	wxopenappreceiveNotify "zerocmf/service/wechat/api/internal/handler/wxopen/app/receiveNotify"
	wxopenappverify "zerocmf/service/wechat/api/internal/handler/wxopen/app/verify"
	"zerocmf/service/wechat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/component_verify_ticket",
				Handler: wxopenappverify.ComponentVerifyTicketHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/wechat"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/receive_notify/:appId",
				Handler: wxopenappreceiveNotify.ReceiveNotifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.ComponentAccessTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/fastRegisterWeApp",
					Handler: wxopenappfastRegisterWeApp.FastRegisterWeAppHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.WxappMiddleware, serverCtx.ComponentAccessTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/login",
					Handler: wxopenapplogin.LoginHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/wechat"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SiteMiddleware, serverCtx.AuthMiddleware, serverCtx.ComponentAccessTokenMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/preAuth",
					Handler: wxopenadmin.PreAuthHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/bindMp",
					Handler: wxopenadmin.BindMpHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/wechat/admin"),
	)
}
