// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	wxapp "zerocmf/service/wechat/api/internal/handler/wxapp"
	"zerocmf/service/wechat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/code2Session",
				Handler: wxapp.Code2SessionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/wxapp"),
	)
}
