// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package server

import (
	"context"

	"zerocmf/service/shop/rpc/internal/logic/shopservice"
	"zerocmf/service/shop/rpc/internal/svc"
	"zerocmf/service/shop/rpc/pb/shop"
)

type ShopServiceServer struct {
	svcCtx *svc.ServiceContext
	shop.UnimplementedShopServiceServer
}

func NewShopServiceServer(svcCtx *svc.ServiceContext) *ShopServiceServer {
	return &ShopServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ShopServiceServer) AutoMigrate(ctx context.Context, in *shop.MigrateReq) (*shop.MigrateReply, error) {
	l := shopservicelogic.NewAutoMigrateLogic(ctx, s.svcCtx)
	return l.AutoMigrate(in)
}
