// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productSkuAttrRelationFieldNames          = builder.RawFieldNames(&ProductSkuAttrRelation{})
	productSkuAttrRelationRows                = strings.Join(productSkuAttrRelationFieldNames, ",")
	productSkuAttrRelationRowsExpectAutoSet   = strings.Join(stringx.Remove(productSkuAttrRelationFieldNames, "`attribute_id`", "`id`"), ",")
	productSkuAttrRelationRowsWithPlaceHolder = strings.Join(stringx.Remove(productSkuAttrRelationFieldNames, "`attribute_id`", "`id`"), "=?,") + "=?"

	cacheProductSkuAttrRelationAttributeIdPrefix = "cache:productSkuAttrRelation:attributeId:"
)

type (
	productSkuAttrRelationModel interface {
		Where(query string, args ...interface{}) *defaultProductSkuAttrRelationModel
		Limit(limit int) *defaultProductSkuAttrRelationModel
		Offset(offset int) *defaultProductSkuAttrRelationModel
		OrderBy(query string) *defaultProductSkuAttrRelationModel
		First(ctx context.Context) (*ProductSkuAttrRelation, error)
		Find(ctx context.Context) ([]*ProductSkuAttrRelation, error)
		Count(ctx context.Context) (int64, error)
		Insert(ctx context.Context, data *ProductSkuAttrRelation) (sql.Result, error)
		FindOne(ctx context.Context, attributeId int64) (*ProductSkuAttrRelation, error)
		Update(ctx context.Context, data *ProductSkuAttrRelation) error
		Delete(ctx context.Context, attributeId int64) error
	}

	defaultProductSkuAttrRelationModel struct {
		sqlc.CachedConn
		table     string
		query     string
		queryArgs []interface{}
		limit     int
		offset    int
		orderBy   string
	}

	ProductSkuAttrRelation struct {
		AttributeId int64 `db:"attribute_id"`
		SkuId       int64 `db:"sku_id"`
		AttrKeyId   int64 `db:"attr_key_id"`
		AttrValId   int64 `db:"attr_val_id"`
		CreatedAt   int64 `db:"created_at"`
		UpdatedAt   int64 `db:"updated_at"`
		DeletedAt   int64 `db:"deleted_at"`
	}
)

func newProductSkuAttrRelationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProductSkuAttrRelationModel {
	return &defaultProductSkuAttrRelationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`product_sku_attr_relation`",
	}
}

func (m *defaultProductSkuAttrRelationModel) withSession(session sqlx.Session) *defaultProductSkuAttrRelationModel {
	return &defaultProductSkuAttrRelationModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`product_sku_attr_relation`",
	}
}

func (m *defaultProductSkuAttrRelationModel) Where(query string, args ...interface{}) *defaultProductSkuAttrRelationModel {
	m.query = query
	m.queryArgs = args
	return m
}

func (m *defaultProductSkuAttrRelationModel) Limit(limit int) *defaultProductSkuAttrRelationModel {
	m.limit = limit
	return m
}

func (m *defaultProductSkuAttrRelationModel) Offset(offset int) *defaultProductSkuAttrRelationModel {
	m.offset = offset
	return m
}

func (m *defaultProductSkuAttrRelationModel) OrderBy(orderBy string) *defaultProductSkuAttrRelationModel {
	m.orderBy = orderBy
	return m
}
func (m *defaultProductSkuAttrRelationModel) Delete(ctx context.Context, attributeId int64) error {
	productSkuAttrRelationAttributeIdKey := fmt.Sprintf("%s%v", cacheProductSkuAttrRelationAttributeIdPrefix, attributeId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `attribute_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, attributeId)
	}, productSkuAttrRelationAttributeIdKey)
	return err
}

func (m *defaultProductSkuAttrRelationModel) FindOne(ctx context.Context, attributeId int64) (*ProductSkuAttrRelation, error) {
	productSkuAttrRelationAttributeIdKey := fmt.Sprintf("%s%v", cacheProductSkuAttrRelationAttributeIdPrefix, attributeId)
	var resp ProductSkuAttrRelation
	err := m.QueryRowCtx(ctx, &resp, productSkuAttrRelationAttributeIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `attribute_id` = ? AND deleted_at = 0 limit 1", productSkuAttrRelationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, attributeId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductSkuAttrRelationModel) Insert(ctx context.Context, data *ProductSkuAttrRelation) (sql.Result, error) {
	productSkuAttrRelationAttributeIdKey := fmt.Sprintf("%s%v", cacheProductSkuAttrRelationAttributeIdPrefix, data.AttributeId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, productSkuAttrRelationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.SkuId, data.AttrKeyId, data.AttrValId, data.CreatedAt, data.UpdatedAt, data.DeletedAt)
	}, productSkuAttrRelationAttributeIdKey)
	return ret, err
}

func (m *defaultProductSkuAttrRelationModel) Update(ctx context.Context, data *ProductSkuAttrRelation) error {
	productSkuAttrRelationAttributeIdKey := fmt.Sprintf("%s%v", cacheProductSkuAttrRelationAttributeIdPrefix, data.AttributeId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `attribute_id` = ?", m.table, productSkuAttrRelationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.SkuId, data.AttrKeyId, data.AttrValId, data.CreatedAt, data.UpdatedAt, data.DeletedAt, data.AttributeId)
	}, productSkuAttrRelationAttributeIdKey)
	return err
}

// 根据条件进行查询一条数据
func (m *defaultProductSkuAttrRelationModel) First(ctx context.Context) (*ProductSkuAttrRelation, error) {
	query := m.query

	queryArgs := m.queryArgs
	orderBy := m.orderBy
	var resp ProductSkuAttrRelation
	sql := fmt.Sprintf("select %s from %s", productSkuAttrRelationRows, m.table)

	if query != "" {
		sql += " where " + query
	}

	// 排序
	if orderBy != "" {
		sql += fmt.Sprintf(" ORDER BY %s", orderBy)
		if orderBy != "" {
			sql += fmt.Sprintf(" %s", orderBy)
		}
	}

	sql += " AND deleted_at = 0 limit 1"

	err := m.QueryRowNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// 根据条件进行列表查询
func (m *defaultProductSkuAttrRelationModel) Find(ctx context.Context) ([]*ProductSkuAttrRelation, error) {

	query := m.query
	queryArgs := m.queryArgs
	orderBy := m.orderBy

	var resp []*ProductSkuAttrRelation
	sql := fmt.Sprintf("select %s from %s", productSkuAttrRelationRows, m.table)

	if query != "" {
		sql += " where " + query + " AND deleted_at = 0"
	} else {
		sql += " where deleted_at = 0"
	}

	// 排序
	if orderBy != "" {
		sql += fmt.Sprintf(" ORDER BY %s", orderBy)
		if orderBy != "" {
			sql += fmt.Sprintf(" %s", orderBy)
		}
	}

	limit := m.limit
	offset := m.offset

	// 查询条件
	if limit > 0 {
		sql += fmt.Sprintf(" LIMIT %d", limit)
	}

	if offset > 0 {
		sql += fmt.Sprintf(" OFFSET %d", offset)
	}

	err := m.QueryRowsNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// 统计字段
func (m *defaultProductSkuAttrRelationModel) Count(ctx context.Context) (int64, error) {
	query := m.query
	queryArgs := m.queryArgs
	sql := fmt.Sprintf("select count(`attribute_id`) from %s", m.table)
	if query != "" {
		sql += " where " + query
	}
	var resp int64
	err := m.QueryRowNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}
func (m *defaultProductSkuAttrRelationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductSkuAttrRelationAttributeIdPrefix, primary)
}

func (m *defaultProductSkuAttrRelationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `attribute_id` = ? AND deleted_at = 0 limit 1", productSkuAttrRelationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductSkuAttrRelationModel) tableName() string {
	return m.table
}
