// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	productAttrKeyFieldNames          = builder.RawFieldNames(&ProductAttrKey{})
	productAttrKeyRows                = strings.Join(productAttrKeyFieldNames, ",")
	productAttrKeyRowsExpectAutoSet   = strings.Join(stringx.Remove(productAttrKeyFieldNames, "`attr_key_id`", "`id`"), ",")
	productAttrKeyRowsWithPlaceHolder = strings.Join(stringx.Remove(productAttrKeyFieldNames, "`attr_key_id`", "`id`"), "=?,") + "=?"

	cacheProductAttrKeyAttrKeyIdPrefix    = "cache:productAttrKey:attrKeyId:"
	cacheProductAttrKeyAttributeKeyPrefix = "cache:productAttrKey:attributeKey:"
)

type (
	productAttrKeyModel interface {
		Where(query string, args ...interface{}) *defaultProductAttrKeyModel
		Limit(limit int) *defaultProductAttrKeyModel
		Offset(offset int) *defaultProductAttrKeyModel
		OrderBy(query string) *defaultProductAttrKeyModel
		First(ctx context.Context) (*ProductAttrKey, error)
		Find(ctx context.Context) ([]*ProductAttrKey, error)
		Count(ctx context.Context) (int64, error)
		Insert(ctx context.Context, data *ProductAttrKey) (sql.Result, error)
		FindOne(ctx context.Context, attrKeyId int64) (*ProductAttrKey, error)
		FindOneByAttributeKey(ctx context.Context, attributeKey string) (*ProductAttrKey, error)
		Update(ctx context.Context, data *ProductAttrKey) error
		Delete(ctx context.Context, attrKeyId int64) error
	}

	defaultProductAttrKeyModel struct {
		sqlc.CachedConn
		table     string
		query     string
		queryArgs []interface{}
		limit     int
		offset    int
		orderBy   string
	}

	ProductAttrKey struct {
		AttrKeyId    int64  `db:"attr_key_id"`
		AttributeKey string `db:"attribute_key"`
		CreatedAt    int64  `db:"created_at"`
		UpdatedAt    int64  `db:"updated_at"`
		DeletedAt    int64  `db:"deleted_at"`
	}
)

func newProductAttrKeyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultProductAttrKeyModel {
	return &defaultProductAttrKeyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`product_attr_key`",
	}
}

func (m *defaultProductAttrKeyModel) withSession(session sqlx.Session) *defaultProductAttrKeyModel {
	return &defaultProductAttrKeyModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`product_attr_key`",
	}
}

func (m *defaultProductAttrKeyModel) Where(query string, args ...interface{}) *defaultProductAttrKeyModel {
	m.query = query
	m.queryArgs = args
	return m
}

func (m *defaultProductAttrKeyModel) Limit(limit int) *defaultProductAttrKeyModel {
	m.limit = limit
	return m
}

func (m *defaultProductAttrKeyModel) Offset(offset int) *defaultProductAttrKeyModel {
	m.offset = offset
	return m
}

func (m *defaultProductAttrKeyModel) OrderBy(orderBy string) *defaultProductAttrKeyModel {
	m.orderBy = orderBy
	return m
}
func (m *defaultProductAttrKeyModel) Delete(ctx context.Context, attrKeyId int64) error {
	data, err := m.FindOne(ctx, attrKeyId)
	if err != nil {
		return err
	}

	productAttrKeyAttrKeyIdKey := fmt.Sprintf("%s%v", cacheProductAttrKeyAttrKeyIdPrefix, attrKeyId)
	productAttrKeyAttributeKeyKey := fmt.Sprintf("%s%v", cacheProductAttrKeyAttributeKeyPrefix, data.AttributeKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `attr_key_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, attrKeyId)
	}, productAttrKeyAttrKeyIdKey, productAttrKeyAttributeKeyKey)
	return err
}

func (m *defaultProductAttrKeyModel) FindOne(ctx context.Context, attrKeyId int64) (*ProductAttrKey, error) {
	productAttrKeyAttrKeyIdKey := fmt.Sprintf("%s%v", cacheProductAttrKeyAttrKeyIdPrefix, attrKeyId)
	var resp ProductAttrKey
	err := m.QueryRowCtx(ctx, &resp, productAttrKeyAttrKeyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `attr_key_id` = ? AND deleted_at = 0 limit 1", productAttrKeyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, attrKeyId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductAttrKeyModel) FindOneByAttributeKey(ctx context.Context, attributeKey string) (*ProductAttrKey, error) {
	productAttrKeyAttributeKeyKey := fmt.Sprintf("%s%v", cacheProductAttrKeyAttributeKeyPrefix, attributeKey)
	var resp ProductAttrKey
	err := m.QueryRowIndexCtx(ctx, &resp, productAttrKeyAttributeKeyKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `attribute_key` = ? AND deleted_at = 0 limit 1", productAttrKeyRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, attributeKey); err != nil {
			return nil, err
		}
		return resp.AttrKeyId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultProductAttrKeyModel) Insert(ctx context.Context, data *ProductAttrKey) (sql.Result, error) {
	productAttrKeyAttrKeyIdKey := fmt.Sprintf("%s%v", cacheProductAttrKeyAttrKeyIdPrefix, data.AttrKeyId)
	productAttrKeyAttributeKeyKey := fmt.Sprintf("%s%v", cacheProductAttrKeyAttributeKeyPrefix, data.AttributeKey)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, productAttrKeyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AttributeKey, data.CreatedAt, data.UpdatedAt, data.DeletedAt)
	}, productAttrKeyAttrKeyIdKey, productAttrKeyAttributeKeyKey)
	return ret, err
}

func (m *defaultProductAttrKeyModel) Update(ctx context.Context, newData *ProductAttrKey) error {
	data, err := m.FindOne(ctx, newData.AttrKeyId)
	if err != nil {
		return err
	}

	productAttrKeyAttrKeyIdKey := fmt.Sprintf("%s%v", cacheProductAttrKeyAttrKeyIdPrefix, data.AttrKeyId)
	productAttrKeyAttributeKeyKey := fmt.Sprintf("%s%v", cacheProductAttrKeyAttributeKeyPrefix, data.AttributeKey)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `attr_key_id` = ?", m.table, productAttrKeyRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.AttributeKey, newData.CreatedAt, newData.UpdatedAt, newData.DeletedAt, newData.AttrKeyId)
	}, productAttrKeyAttrKeyIdKey, productAttrKeyAttributeKeyKey)
	return err
}

// 根据条件进行查询一条数据
func (m *defaultProductAttrKeyModel) First(ctx context.Context) (*ProductAttrKey, error) {
	query := m.query

	queryArgs := m.queryArgs
	orderBy := m.orderBy
	var resp ProductAttrKey
	sql := fmt.Sprintf("select %s from %s", productAttrKeyRows, m.table)

	if query != "" {
		sql += " where " + query
	}

	// 排序
	if orderBy != "" {
		sql += fmt.Sprintf(" ORDER BY %s", orderBy)
		if orderBy != "" {
			sql += fmt.Sprintf(" %s", orderBy)
		}
	}

	sql += " AND deleted_at = 0 limit 1"

	err := m.QueryRowNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// 根据条件进行列表查询
func (m *defaultProductAttrKeyModel) Find(ctx context.Context) ([]*ProductAttrKey, error) {

	query := m.query
	queryArgs := m.queryArgs
	orderBy := m.orderBy

	var resp []*ProductAttrKey
	sql := fmt.Sprintf("select %s from %s", productAttrKeyRows, m.table)

	if query != "" {
		sql += " where " + query + " AND deleted_at = 0"
	} else {
		sql += " where deleted_at = 0"
	}

	// 排序
	if orderBy != "" {
		sql += fmt.Sprintf(" ORDER BY %s", orderBy)
		if orderBy != "" {
			sql += fmt.Sprintf(" %s", orderBy)
		}
	}

	limit := m.limit
	offset := m.offset

	// 查询条件
	if limit > 0 {
		sql += fmt.Sprintf(" LIMIT %d", limit)
	}

	if offset > 0 {
		sql += fmt.Sprintf(" OFFSET %d", offset)
	}

	err := m.QueryRowsNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// 统计字段
func (m *defaultProductAttrKeyModel) Count(ctx context.Context) (int64, error) {
	query := m.query
	queryArgs := m.queryArgs
	sql := fmt.Sprintf("select count(`attr_key_id`) from %s", m.table)
	if query != "" {
		sql += " where " + query
	}
	var resp int64
	err := m.QueryRowNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}
func (m *defaultProductAttrKeyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheProductAttrKeyAttrKeyIdPrefix, primary)
}

func (m *defaultProductAttrKeyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `attr_key_id` = ? AND deleted_at = 0 limit 1", productAttrKeyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultProductAttrKeyModel) tableName() string {
	return m.table
}
