// Code generated by goctl. DO NOT EDIT.
// Source: shop.proto

package server

import (
	"context"

	"zerocmf/service/shop/rpc/internal/logic/productservice"
	"zerocmf/service/shop/rpc/internal/svc"
	"zerocmf/service/shop/rpc/pb/shop"
)

type ProductServiceServer struct {
	svcCtx *svc.ServiceContext
	shop.UnimplementedProductServiceServer
}

func NewProductServiceServer(svcCtx *svc.ServiceContext) *ProductServiceServer {
	return &ProductServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServiceServer) ProductGet(ctx context.Context, in *shop.ProductGetReq) (*shop.ProductListResp, error) {
	l := productservicelogic.NewProductGetLogic(ctx, s.svcCtx)
	return l.ProductGet(in)
}

func (s *ProductServiceServer) ProductShow(ctx context.Context, in *shop.ProductShowReq) (*shop.ProductResp, error) {
	l := productservicelogic.NewProductShowLogic(ctx, s.svcCtx)
	return l.ProductShow(in)
}

func (s *ProductServiceServer) ProductSave(ctx context.Context, in *shop.ProductSaveReq) (*shop.ProductSaveResp, error) {
	l := productservicelogic.NewProductSaveLogic(ctx, s.svcCtx)
	return l.ProductSave(in)
}
