// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package migrate

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MigrateClient is the client API for Migrate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MigrateClient interface {
	// Sends a greeting
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateReply, error)
}

type migrateClient struct {
	cc grpc.ClientConnInterface
}

func NewMigrateClient(cc grpc.ClientConnInterface) MigrateClient {
	return &migrateClient{cc}
}

func (c *migrateClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateReply, error) {
	out := new(MigrateReply)
	err := c.cc.Invoke(ctx, "/migrate.Migrate/Migrate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigrateServer is the server API for Migrate service.
// All implementations must embed UnimplementedMigrateServer
// for forward compatibility
type MigrateServer interface {
	// Sends a greeting
	Migrate(context.Context, *MigrateRequest) (*MigrateReply, error)
	mustEmbedUnimplementedMigrateServer()
}

// UnimplementedMigrateServer must be embedded to have forward compatible implementations.
type UnimplementedMigrateServer struct {
}

func (UnimplementedMigrateServer) Migrate(context.Context, *MigrateRequest) (*MigrateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedMigrateServer) mustEmbedUnimplementedMigrateServer() {}

// UnsafeMigrateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigrateServer will
// result in compilation errors.
type UnsafeMigrateServer interface {
	mustEmbedUnimplementedMigrateServer()
}

func RegisterMigrateServer(s grpc.ServiceRegistrar, srv MigrateServer) {
	s.RegisterService(&Migrate_ServiceDesc, srv)
}

func _Migrate_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigrateServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/migrate.Migrate/Migrate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigrateServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Migrate_ServiceDesc is the grpc.ServiceDesc for Migrate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migrate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "migrate.Migrate",
	HandlerType: (*MigrateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Migrate",
			Handler:    _Migrate_Migrate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "migrate.proto",
}
