// Code generated by goctl. DO NOT EDIT.
// Source: lowcode.proto

package lowcodeclient

import (
	"context"

	"zerocmf/service/lowcode/rpc/types/lowcode"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SiteReply = lowcode.SiteReply
	SiteReq   = lowcode.SiteReq

	Lowcode interface {
		AutoMigrate(ctx context.Context, in *SiteReq, opts ...grpc.CallOption) (*SiteReply, error)
	}

	defaultLowcode struct {
		cli zrpc.Client
	}
)

func NewLowcode(cli zrpc.Client) Lowcode {
	return &defaultLowcode{
		cli: cli,
	}
}

func (m *defaultLowcode) AutoMigrate(ctx context.Context, in *SiteReq, opts ...grpc.CallOption) (*SiteReply, error) {
	client := lowcode.NewLowcodeClient(m.cli.Conn())
	return client.AutoMigrate(ctx, in, opts...)
}
