// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"gincmf/service/user/rpc/internal/logic"
	"gincmf/service/user/rpc/internal/svc"
	"gincmf/service/user/rpc/types"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	userclient.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Get(ctx context.Context, in *userclient.UserRequest) (*userclient.UserReply, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *UserServer) Init(ctx context.Context, in *userclient.InitRequest) (*userclient.InitReply, error) {
	l := logic.NewInitLogic(ctx, s.svcCtx)
	return l.Init(in)
}
