// Code generated by goctl. DO NOT EDIT.
// Source: tenant.proto

package server

import (
	"context"

	"zerocmf/service/tenant/rpc/internal/logic"
	"zerocmf/service/tenant/rpc/internal/svc"
	"zerocmf/service/tenant/rpc/types/tenant"
)

type TenantServer struct {
	svcCtx *svc.ServiceContext
	tenant.UnimplementedTenantServer
}

func NewTenantServer(svcCtx *svc.ServiceContext) *TenantServer {
	return &TenantServer{
		svcCtx: svcCtx,
	}
}

func (s *TenantServer) Get(ctx context.Context, in *tenant.CurrentUserReq) (*tenant.UserReply, error) {
	l := logic.NewGetLogic(ctx, s.svcCtx)
	return l.Get(in)
}

func (s *TenantServer) RegisterUser(ctx context.Context, in *tenant.RegisterReq) (*tenant.UserReply, error) {
	l := logic.NewRegisterUserLogic(ctx, s.svcCtx)
	return l.RegisterUser(in)
}

func (s *TenantServer) CheckUser(ctx context.Context, in *tenant.CheckUserReq) (*tenant.CheckUserReply, error) {
	l := logic.NewCheckUserLogic(ctx, s.svcCtx)
	return l.CheckUser(in)
}

func (s *TenantServer) RemoveSiteUser(ctx context.Context, in *tenant.RemoveSiteUserReq) (*tenant.RemoveSiteUserReply, error) {
	l := logic.NewRemoveSiteUserLogic(ctx, s.svcCtx)
	return l.RemoveSiteUser(in)
}

func (s *TenantServer) BindMp(ctx context.Context, in *tenant.BindMpReq) (*tenant.BindMpReply, error) {
	l := logic.NewBindMpLogic(ctx, s.svcCtx)
	return l.BindMp(in)
}

func (s *TenantServer) GetSiteMp(ctx context.Context, in *tenant.SiteMpReq) (*tenant.SiteMpReply, error) {
	l := logic.NewGetSiteMpLogic(ctx, s.svcCtx)
	return l.GetSiteMp(in)
}

func (s *TenantServer) ShowMp(ctx context.Context, in *tenant.ShowMpData) (*tenant.ShowMpData, error) {
	l := logic.NewShowMpLogic(ctx, s.svcCtx)
	return l.ShowMp(in)
}
