// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type AssetsRequest struct {
	Type string `form:"type,optional,default=0"`
}

type OptionRequest struct {
	SiteName           string `json:"site_name,optional"`
	AdminPassword      string `json:"admin_password,optional"`
	SiteSeoTitle       string `json:"site_seo_title,optional"`
	SiteSeoKeywords    string `json:"site_seo_keywords,optional"`
	SiteSeoDescription string `json:"site_seo_description,optional"`
	SiteIcp            string `json:"site_icp,optional"`
	SiteGwa            string `json:"site_gwa,optional"`
	SiteAdminEmail     string `json:"site_admin_email,optional"`
	SiteAnalytics      string `json:"site_analytics,optional"`
	OpenRegistration   int    `json:"open_registration,optional"`
}
