// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: pb/shop.proto

package shop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CategoryGetReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ParentId  int64   `protobuf:"varint,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"`
	ListOrder float64 `protobuf:"fixed64,3,opt,name=ListOrder,proto3" json:"ListOrder,omitempty"`
	Status    int32   `protobuf:"varint,4,opt,name=Status,proto3" json:"Status,omitempty"`
	Current   int32   `protobuf:"varint,5,opt,name=Current,proto3" json:"Current,omitempty"`
	PageSize  int32   `protobuf:"varint,6,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
}

func (x *CategoryGetReq) Reset() {
	*x = CategoryGetReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryGetReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryGetReq) ProtoMessage() {}

func (x *CategoryGetReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryGetReq.ProtoReflect.Descriptor instead.
func (*CategoryGetReq) Descriptor() ([]byte, []int) {
	return file_pb_shop_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryGetReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryGetReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CategoryGetReq) GetListOrder() float64 {
	if x != nil {
		return x.ListOrder
	}
	return 0
}

func (x *CategoryGetReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CategoryGetReq) GetCurrent() int32 {
	if x != nil {
		return x.Current
	}
	return 0
}

func (x *CategoryGetReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CategoryShowReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CategoryShowReq) Reset() {
	*x = CategoryShowReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryShowReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryShowReq) ProtoMessage() {}

func (x *CategoryShowReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryShowReq.ProtoReflect.Descriptor instead.
func (*CategoryShowReq) Descriptor() ([]byte, []int) {
	return file_pb_shop_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryShowReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CategorySaveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId  int64   `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Name      string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Icon      string  `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Desc      string  `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	Status    int32   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	ListOrder float64 `protobuf:"fixed64,7,opt,name=listOrder,proto3" json:"listOrder,omitempty"`
}

func (x *CategorySaveReq) Reset() {
	*x = CategorySaveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategorySaveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorySaveReq) ProtoMessage() {}

func (x *CategorySaveReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorySaveReq.ProtoReflect.Descriptor instead.
func (*CategorySaveReq) Descriptor() ([]byte, []int) {
	return file_pb_shop_proto_rawDescGZIP(), []int{2}
}

func (x *CategorySaveReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategorySaveReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CategorySaveReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategorySaveReq) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategorySaveReq) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CategorySaveReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CategorySaveReq) GetListOrder() float64 {
	if x != nil {
		return x.ListOrder
	}
	return 0
}

type CategoryDelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CategoryDelReq) Reset() {
	*x = CategoryDelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shop_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryDelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryDelReq) ProtoMessage() {}

func (x *CategoryDelReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shop_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryDelReq.ProtoReflect.Descriptor instead.
func (*CategoryDelReq) Descriptor() ([]byte, []int) {
	return file_pb_shop_proto_rawDescGZIP(), []int{3}
}

func (x *CategoryDelReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CategoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 创建分类的响应信息
	Id        int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId  int64   `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Name      string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Path      string  `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Icon      string  `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Desc      string  `protobuf:"bytes,6,opt,name=desc,proto3" json:"desc,omitempty"`
	Status    int32   `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	ListOrder float64 `protobuf:"fixed64,8,opt,name=listOrder,proto3" json:"listOrder,omitempty"`
	CreatedAt int64   `protobuf:"varint,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt int64   `protobuf:"varint,10,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *CategoryResp) Reset() {
	*x = CategoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shop_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryResp) ProtoMessage() {}

func (x *CategoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shop_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryResp.ProtoReflect.Descriptor instead.
func (*CategoryResp) Descriptor() ([]byte, []int) {
	return file_pb_shop_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryResp) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *CategoryResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryResp) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CategoryResp) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *CategoryResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *CategoryResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CategoryResp) GetListOrder() float64 {
	if x != nil {
		return x.ListOrder
	}
	return 0
}

func (x *CategoryResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CategoryResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CategoryListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data  []*CategoryResp `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Total int64           `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *CategoryListResp) Reset() {
	*x = CategoryListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_shop_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResp) ProtoMessage() {}

func (x *CategoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_shop_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResp.ProtoReflect.Descriptor instead.
func (*CategoryListResp) Descriptor() ([]byte, []int) {
	return file_pb_shop_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryListResp) GetData() []*CategoryResp {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CategoryListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_pb_shop_proto protoreflect.FileDescriptor

var file_pb_shop_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x62, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x73, 0x68, 0x6f, 0x70, 0x22, 0xac, 0x01, 0x0a, 0x0e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x4c, 0x69, 0x73,
	0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x22, 0x21, 0x0a, 0x0f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xaf, 0x01, 0x0a, 0x0f, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x63, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x6c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xfc, 0x01, 0x0a, 0x0c,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x50, 0x0a, 0x10, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73,
	0x68, 0x6f, 0x70, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x32, 0xfd, 0x01, 0x0a,
	0x0f, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3b, 0x0a, 0x0b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x47, 0x65, 0x74, 0x12,
	0x14, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a,
	0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x68, 0x6f, 0x77, 0x12, 0x15, 0x2e,
	0x73, 0x68, 0x6f, 0x70, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x68, 0x6f,
	0x77, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x53, 0x61, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x12, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0b, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x44,
	0x65, 0x6c, 0x12, 0x14, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x44, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x73, 0x68, 0x6f, 0x70, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x08, 0x5a, 0x06,
	0x2e, 0x2f, 0x73, 0x68, 0x6f, 0x70, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_shop_proto_rawDescOnce sync.Once
	file_pb_shop_proto_rawDescData = file_pb_shop_proto_rawDesc
)

func file_pb_shop_proto_rawDescGZIP() []byte {
	file_pb_shop_proto_rawDescOnce.Do(func() {
		file_pb_shop_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_shop_proto_rawDescData)
	})
	return file_pb_shop_proto_rawDescData
}

var file_pb_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pb_shop_proto_goTypes = []interface{}{
	(*CategoryGetReq)(nil),   // 0: shop.CategoryGetReq
	(*CategoryShowReq)(nil),  // 1: shop.CategoryShowReq
	(*CategorySaveReq)(nil),  // 2: shop.CategorySaveReq
	(*CategoryDelReq)(nil),   // 3: shop.CategoryDelReq
	(*CategoryResp)(nil),     // 4: shop.CategoryResp
	(*CategoryListResp)(nil), // 5: shop.CategoryListResp
}
var file_pb_shop_proto_depIdxs = []int32{
	4, // 0: shop.CategoryListResp.data:type_name -> shop.CategoryResp
	0, // 1: shop.CategoryService.CategoryGet:input_type -> shop.CategoryGetReq
	1, // 2: shop.CategoryService.CategoryShow:input_type -> shop.CategoryShowReq
	2, // 3: shop.CategoryService.CategorySave:input_type -> shop.CategorySaveReq
	3, // 4: shop.CategoryService.CategoryDel:input_type -> shop.CategoryDelReq
	5, // 5: shop.CategoryService.CategoryGet:output_type -> shop.CategoryListResp
	4, // 6: shop.CategoryService.CategoryShow:output_type -> shop.CategoryResp
	4, // 7: shop.CategoryService.CategorySave:output_type -> shop.CategoryResp
	4, // 8: shop.CategoryService.CategoryDel:output_type -> shop.CategoryResp
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_shop_proto_init() }
func file_pb_shop_proto_init() {
	if File_pb_shop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_shop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryGetReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryShowReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategorySaveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shop_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryDelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shop_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_shop_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_shop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_shop_proto_goTypes,
		DependencyIndexes: file_pb_shop_proto_depIdxs,
		MessageInfos:      file_pb_shop_proto_msgTypes,
	}.Build()
	File_pb_shop_proto = out.File
	file_pb_shop_proto_rawDesc = nil
	file_pb_shop_proto_goTypes = nil
	file_pb_shop_proto_depIdxs = nil
}
