// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "gincmf/service/user/api/internal/handler/user"
	"gincmf/service/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: user.IndexHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: user.GetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/current_user",
				Handler: user.CurrentUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/save",
				Handler: user.SaveHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/app/user"),
	)
}
