// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package adminclient

import (
	"context"

	"zerocmf/service/admin/rpc/types/admin"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminMenu       = admin.AdminMenu
	AdminMenuReply  = admin.AdminMenuReply
	AdminMenuReq    = admin.AdminMenuReq
	EncryptUidReply = admin.EncryptUidReply
	EncryptUidReq   = admin.EncryptUidReq
	SiteReply       = admin.SiteReply
	SiteReq         = admin.SiteReq

	Admin interface {
		GetMenus(ctx context.Context, in *AdminMenuReq, opts ...grpc.CallOption) (*AdminMenuReply, error)
		AutoMigrate(ctx context.Context, in *SiteReq, opts ...grpc.CallOption) (*SiteReply, error)
		EncryptUid(ctx context.Context, in *EncryptUidReq, opts ...grpc.CallOption) (*EncryptUidReply, error)
	}

	defaultAdmin struct {
		cli zrpc.Client
	}
)

func NewAdmin(cli zrpc.Client) Admin {
	return &defaultAdmin{
		cli: cli,
	}
}

func (m *defaultAdmin) GetMenus(ctx context.Context, in *AdminMenuReq, opts ...grpc.CallOption) (*AdminMenuReply, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.GetMenus(ctx, in, opts...)
}

func (m *defaultAdmin) AutoMigrate(ctx context.Context, in *SiteReq, opts ...grpc.CallOption) (*SiteReply, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.AutoMigrate(ctx, in, opts...)
}

func (m *defaultAdmin) EncryptUid(ctx context.Context, in *EncryptUidReq, opts ...grpc.CallOption) (*EncryptUidReply, error) {
	client := admin.NewAdminClient(m.cli.Conn())
	return client.EncryptUid(ctx, in, opts...)
}
