// Code generated by goctl. DO NOT EDIT.
package types

type FastRegisterWeAppReq struct {
	Name               string `json:"name"`
	Code               string `json:"code"`
	CodeType           int    `json:"code_type"`
	LegalPersonaWechat string `json:"legal_persona_wechat"`
	LegalPersonaName   string `json:"legal_persona_name"`
	ComponentPhone     string `json:"component_phone,optional"`
	Pwd                string `json:"pwd"`
}

type ReceiveNotifyReq struct {
	AppId string `path:"appId"`
}

type LoginReq struct {
	AppId  string `form:"appId"`
	JsCode string `form:"jsCode"`
}

type PreAuthReq struct {
	Redirect string `form:"redirect,optional"`
}

type BindMpReq struct {
	AuthCode string `form:"authCode"`
	Typ      string `form:"type"`
}
