// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	adminMenu "gincmf/service/admin/api/internal/handler/adminMenu"
	assets "gincmf/service/admin/api/internal/handler/assets"
	option "gincmf/service/admin/api/internal/handler/option"
	"gincmf/service/admin/api/internal/svc"
	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin_menu",
				Handler: adminMenu.GetHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/assets",
				Handler: assets.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/assets",
				Handler: assets.StoreHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/settings",
				Handler: option.GetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/settings",
				Handler: option.StoreHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin"),
	)
}
