// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type UserReq struct {
	Id string `path:"id"`
}
