// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"zerocmf/service/admin/rpc/internal/logic"
	"zerocmf/service/admin/rpc/internal/svc"
	"zerocmf/service/admin/rpc/types/admin"
)

type AdminServer struct {
	svcCtx *svc.ServiceContext
	admin.UnimplementedAdminServer
}

func NewAdminServer(svcCtx *svc.ServiceContext) *AdminServer {
	return &AdminServer{
		svcCtx: svcCtx,
	}
}

func (s *AdminServer) AutoMigrate(ctx context.Context, in *admin.SiteReq) (*admin.SiteReply, error) {
	l := logic.NewAutoMigrateLogic(ctx, s.svcCtx)
	return l.AutoMigrate(in)
}
