// Code generated by goctl. DO NOT EDIT.
package types

type CategoryGetReq struct {
	Name      string   `form:"name,optional"`
	ParentId  int64    `form:"parentId,optional"`
	ListOrder *float64 `form:"listOrder,optional"`
	Status    *int     `form:"status,optional"`
}

type CategoryTreeDataReq struct {
	Name     string `form:"name,optional"`
	Status   *int   `form:"status,optional"`
	IgnoreId *int64 `form:"ignoreId,optional"`
}

type CategoryShowReq struct {
	Id int64 `path:"id"`
}

type CategorySaveReq struct {
	Id        int64    `path:"id,optional"`
	ParentId  int64    `json:"parentId,optional"`
	Name      string   `json:"name"`
	Icon      string   `json:"icon,optional"`
	Desc      string   `json:"desc,optional"`
	ListOrder *float64 `json:"listOrder,optional"`
	Status    *int     `json:"status,optional"`
}

type CategoryDelReq struct {
	Id int64 `path:"id"`
}

type CategoryBatchDelReq struct {
}

type GoodsGetReq struct {
}

type GoodsShowReq struct {
}

type GoodsStoreReq struct {
}

type GoodsEditReq struct {
}

type GoodsDelReq struct {
}

type GoodsBatchDelReq struct {
}
